from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from reportlab.lib.enums import TA_CENTER

out="output/pdf/Atlas_do_Pescado_Etapa_2_Relatorio_Tecnico.pdf"
doc=SimpleDocTemplate(out,pagesize=A4,rightMargin=1.7*cm,leftMargin=1.7*cm,topMargin=1.6*cm,bottomMargin=1.5*cm)
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name="Title2",parent=styles["Title"],fontSize=21,leading=25,textColor=colors.HexColor("#0b5261"),alignment=TA_CENTER,spaceAfter=18))
styles.add(ParagraphStyle(name="H2x",parent=styles["Heading2"],fontSize=14,leading=18,textColor=colors.HexColor("#0b5261"),spaceBefore=10,spaceAfter=7))
styles.add(ParagraphStyle(name="Bodyx",parent=styles["BodyText"],fontSize=9.5,leading=13,spaceAfter=6))
styles.add(ParagraphStyle(name="Smallx",parent=styles["BodyText"],fontSize=8,leading=10))
S=[]
S += [Paragraph("ATLAS DO PESCADO",styles["Title2"]),Paragraph("Etapa 2 - Migração determinística para Comércio Exterior e Dados Municipais",styles["Heading1"]),Paragraph("Relatório técnico de implementação, testes e validação<br/>29 de setembro de 2026",styles["Bodyx"]),Spacer(1,8)]
S += [Paragraph("1. Resultado executivo",styles["H2x"]),Paragraph("A camada determinística foi ampliada sem Atlantic AI generativo, API OpenAI, backend, banco, serviços pagos, execução de R/Python ou alteração visual. O núcleo agora oferece consultas estruturadas reutilizáveis para IBGE Aquicultura, MPA, FAO, MDIC Comércio Exterior e IBGE Municípios.",styles["Bodyx"])]
S += [Paragraph("2. Arquivos modificados e novos",styles["H2x"])]
rows=[["Arquivo","Alteração"],["dist/data-query.js","Novas funções queryTrade, queryMunicipal e compareMunicipal; suporte a mapas municipais; validações e metadados."],["dist/query-artifacts.js","rCode ampliado para MDIC e municípios; gráficos e mapas continuam compatíveis."],["dist/improvements.js","tradeMatching e municipalRows passaram a consumir a camada determinística."],["test-data-query.cjs","10 blocos de testes cobrindo Etapa 1, comércio, municípios, mapas, ausência e R."],["output/pdf/...","Relatório técnico desta Etapa 2."]]
t=Table([[Paragraph(x,styles["Smallx"]) for x in row] for row in rows],colWidths=[5.2*cm,11.5*cm]);t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),colors.HexColor("#0b5261")),("TEXTCOLOR",(0,0),(-1,0),colors.white),("GRID",(0,0),(-1,-1),.3,colors.HexColor("#b7cdd1")),("VALIGN",(0,0),(-1,-1),"TOP"),("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white,colors.HexColor("#eef6f7")]),("LEFTPADDING",(0,0),(-1,-1),6),("RIGHTPADDING",(0,0),(-1,-1),6)]));S += [t]
S += [Paragraph("3. Contrato determinístico",styles["H2x"]),Paragraph("<b>queryTrade(data, { indicator, from, to, flow?, partner?, uf?, ncm? })</b> retorna dataset, filtros, indicador, unidade, período, valores anuais, linhas filtradas, fonte, URL, recorte, limitações e avisos. Indicadores aceitos: fob_usd e net_weight_t.",styles["Bodyx"]),Paragraph("<b>queryMunicipal(data, { year?, uf?, municipality?, product?, indicator? })</b> retorna linhas municipais, total do recorte, municípios observados e metadados. A cobertura é 2024; ausência retorna null.",styles["Bodyx"]),Paragraph("<b>compareMunicipal(data, { municipalities, product?, indicator? })</b> produz séries comparáveis. compare permanece compatível com a Etapa 1 e rejeita geometrias/datasets incompatíveis.",styles["Bodyx"]),Paragraph("<b>getMapValues</b> fornece valores por UF para comércio e por código municipal para aquicultura municipal, com arquivo de geometria e avisos.",styles["Bodyx"])]
S += [Paragraph("4. Exemplos",styles["H2x"]),Paragraph('<font name="Courier">queryTrade(data, {dataset:"mdic-trade", indicator:"fob_usd", from:2024, to:2024, flow:"exp", uf:"15"})</font><br/>Saída: série de 2024 em US$ FOB, filtro UF 15, fonte MDIC/Comex Stat e limitações do capítulo NCM 03.',styles["Bodyx"]),Paragraph('<font name="Courier">queryMunicipal(data, {uf:"15", product:"32877"})</font><br/>Saída: linhas de municípios do Pará para Tilápia, produção em toneladas, ano 2024 e ausência preservada como null.',styles["Bodyx"])]
S += [Paragraph("5. Regras preservadas",styles["H2x"]),Paragraph("Ausência, sigilo e proteção não são zero; 2026 do MDIC é parcial (janeiro-agosto); peso líquido e FOB não são misturados; país é parceiro; UF do comércio é UF do produto e não município da empresa; NCM permanece separado de produto; municípios não recebem agregados duplicados; comparações exigem o mesmo dataset e indicador; não há dependência de dados externos em tempo real.",styles["Bodyx"])]
S += [Paragraph("6. Testes e validação",styles["H2x"]),Paragraph("Comando executado: node test-data-query.cjs. Resultado: 10 blocos aprovados, 0 falhas. Também foram executados node --check nos módulos modificados e git diff --check.",styles["Bodyx"])]
val=[["Área","Casos validados","Resultado"],["Etapa 1","Pará/Maranhão 2018-2024; gráfico; mapa UF; R; ausência; catálogo","Aprovado; valores preservados."],["Comércio","Ano, fluxo, FOB, peso líquido, país, UF, NCM, combinação, 2026 parcial e ausência","Aprovado."],["Municípios","UF, município, produto, combinações, 2024, mapa, ausência e duplicação","Aprovado."],["R/mapas","Mapa MDIC por UF, mapa municipal e geração não executável de R","Aprovado."]]
t=Table([[Paragraph(x,styles["Smallx"]) for x in row] for row in val],colWidths=[3*cm,9.5*cm,4.2*cm]);t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),colors.HexColor("#0b5261")),("TEXTCOLOR",(0,0),(-1,0),colors.white),("GRID",(0,0),(-1,-1),.3,colors.HexColor("#b7cdd1")),("VALIGN",(0,0),(-1,-1),"TOP"),("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white,colors.HexColor("#eef6f7")]) ]));S += [t]
S += [Paragraph("7. Divergências e limitações",styles["H2x"]),Paragraph("Não houve divergência numérica nos casos automatizados. A interface continua exibindo os mesmos recortes e aparência. A base municipal é somente 2024. O painel de comércio continua com o escopo preparado do capítulo NCM 03; produtos processados em outros capítulos não entram nesta cópia. A integração visual completa de todos os rankings/exportações ainda depende de futuras revisões, embora os filtros principais já usem a camada.",styles["Bodyx"])]
S += [Paragraph("8. Versão e encerramento",styles["H2x"]),Paragraph("Versão anterior confirmada: 7, commit 7f5d1fb077f8053f48b469ae844d67f2bd01d006. Esta Etapa 2 está pronta para ser publicada como a próxima versão do Site após o commit desta implementação. A Etapa 1 continua funcionando. O trabalho para aqui e não inicia a Etapa 3.",styles["Bodyx"])]
def footer(canvas,doc):
    canvas.saveState();canvas.setFont("Helvetica",8);canvas.setFillColor(colors.HexColor("#55737b"));canvas.drawString(1.7*cm,0.8*cm,"Atlas do Pescado · Etapa 2");canvas.drawRightString(A4[0]-1.7*cm,0.8*cm,f"Página {doc.page}");canvas.restoreState()
doc.build(S,onFirstPage=footer,onLaterPages=footer)
print(out)
