const assert=require('node:assert/strict'),fs=require('node:fs');
const Q=require('../dist/regions-core.js');const t=JSON.parse(fs.readFileSync('dist/regions.json')),m=JSON.parse(fs.readFileSync('dist/municipal.json'));
let count=0;function test(label,fn){fn();count++;console.log('PASS '+label)}
test('Six states and all 566 municipalities, unique official memberships',()=>{assert.deepEqual(Object.keys(t.states).sort(),['11','13','15','16','21','28']);assert.equal(Q.territories(t).length,566);for(const s of Object.values(t.states)){const ids=Object.values(s.regions).flatMap(r=>r.municipalities);assert.equal(ids.length,Object.keys(s.municipalities).length);assert.equal(new Set(ids).size,ids.length);for(const id of ids)assert.ok(s.regions[s.municipalities[id].region].municipalities.includes(id))}});
test('State → region → municipality → observations for every region',()=>{for(const s of Object.values(t.states))for(const r of Object.values(s.regions)){const places=Q.territories(t,{state:s.id,region:r.id});assert.equal(places.length,r.municipalities.length);for(const p of places){const result=Q.query(t,m,{state:s.id,region:r.id,municipality:p.id});assert.ok(result.rows.every(row=>row.id===p.id));}}});
test('Bragança resolves to its official immediate region',()=>{const b=t.states['15'].municipalities['1501709'];assert.equal(t.states['15'].regions[b.region].name,'Bragança')});
test('Existing observations preserved and only launch states selected',()=>{const result=Q.query(t,m);const original=m.rows.filter(r=>t.states[r[0].slice(0,2)]&&Number.isFinite(r[2]));assert.equal(result.rows.length,original.length);assert.equal(result.value,original.reduce((s,r)=>s+r[2],0))});
test('Municipality with no observation stays null, never zero',()=>{const p=Q.territories(t).find(p=>!Q.query(t,m,{municipality:p.id}).rows.length);assert.ok(p);assert.equal(Q.query(t,m,{municipality:p.id}).value,null)});
test('Region with no observations stays null (empty base fixture)',()=>{const r=Object.values(t.states['16'].regions)[0];const x=Q.query(t,{...m,rows:[]},{state:'16',region:r.id});assert.equal(x.value,null);assert.equal(x.status,'absent')});
test('Numeric zero is preserved when explicitly present',()=>{const p=Q.territories(t)[0];const x=Q.query(t,{...m,rows:[[p.id,'32876',0]]},{municipality:p.id});assert.equal(x.value,0);assert.equal(x.rows.length,1)});
test('Suppressed, missing and nonnumeric values are not coerced',()=>{const p=Q.territories(t)[0];const x=Q.query(t,{...m,rows:['...',null,'',undefined].map(v=>[p.id,'32876',v])},{municipality:p.id});assert.equal(x.value,null);assert.notEqual(Q.messages.suppressed,Q.messages.unreported)});
test('Unavailable period has a distinct message',()=>{assert.equal(Q.query(t,m,{year:2023}).status,'period')});
test('Open source passes provenance gate',()=>{for(const d of t.datasets)assert.ok(Q.permitted(d)&&Q.exportable(d))});
test('Conditional source requires conditions to be satisfied',()=>{const d={...t.datasets[0],status:'CONDICIONADO',condicoes_atendidas:false};assert.equal(Q.permitted(d),false);d.condicoes_atendidas=true;assert.ok(Q.permitted(d))});
test('Unverified, restricted and reference sources cannot enter operation',()=>{for(const change of [{licenca_verificada:false},{licenca_url:''},{status:'REFERÊNCIA'},{status:'NÃO UTILIZAR'},{tipo_de_acesso:'Restrito'}]){const copy=structuredClone(t);Object.assign(copy.datasets[0],change);assert.equal(Q.query(copy,m).value,null);assert.equal(Q.permitted(copy.datasets[0]),false)}});
test('CSV includes provenance, transformations and source URL',()=>{const csv=Q.csv(t,Q.query(t,m,{state:'15'}).rows);for(const key of ['fonte','licenca','data_acesso','transformacao','limitacoes','https://sidra.ibge.gov.br/tabela/3940'])assert.ok(csv.includes(key))});
test('Export blocked without redistribution permission',()=>{const copy=structuredClone(t);copy.datasets[0].redistribuicao=false;assert.throws(()=>Q.csv(copy,[]))});
test('Geometries cover every official municipality in launch states',()=>{for(const s of Object.values(t.states)){const geo=JSON.parse(fs.readFileSync(`dist/municipios/${s.id}.geojson`));const ids=new Set(geo.features.map(f=>String(f.properties.code)));for(const id of Object.keys(s.municipalities))assert.ok(ids.has(id),id)}});
console.log(`${count} tests passed`);
