"""Aggregate licensed Mendeley v1 records exactly; no inferred taxa, capture origin or missing-day zeros."""
from pathlib import Path
from decimal import Decimal
from collections import defaultdict
from datetime import date
import csv,json,hashlib
root=Path(__file__).resolve().parents[1];d=root/'dist';src=d/'downloads/sources/santarem-mendeley-v1-original.csv'
expected='eeb8e1fa310dc26fee7dfcfe0dc95b0be43e8bdabe07ce5715c85ae160b04122'
assert hashlib.sha256(src.read_bytes()).hexdigest()==expected
raw=list(csv.DictReader(src.open()));assert len(raw)==105092 and len({r['ID'] for r in raw})==len(raw)
groups=defaultdict(lambda:[Decimal(0),0,set()]);labels={};years=defaultdict(set);total=Decimal(0)
for r in raw:
 dt=date.fromisoformat(r['DATE']);v=Decimal(r['Weight (metric ton)']);assert v>=0 and v.is_finite()
 label=r['Fish’s Popular name'].strip();key=label.casefold();labels.setdefault(key,label);g=groups[(dt.year,key)];g[0]+=v;g[1]+=1;g[2].add(dt.isoformat());years[dt.year].add(dt.isoformat());total+=v
rows=[dict(source_id='santarem',codigo_ibge='1506807',municipio='Santarém',uf='PA',ano=y,especie=labels[k],nome_comum=labels[k],desembarque_t=float(v),registros=count,dias_registrados=len(days),esforco_horas=None) for (y,k),(v,count,days) in sorted(groups.items())]
source='https://data.mendeley.com/datasets/ntprfhdypn/1'
meta=dict(id='pesca-municipal-santarem',title='Desembarques registrados na Feira do Pescado de Santarém',source=source,doi='10.17632/ntprfhdypn.1',license='CC BY 4.0',license_url='https://creativecommons.org/licenses/by/4.0/',license_evidence=source,citation='Souza, Keid; Alves, Enoque; Feitosa, Annita; Alves, Vânia; Menezes, Layla; Pantoja, Celson; Santos, Edivaldo (2024). Mendeley Data, v1. DOI: 10.17632/ntprfhdypn.1.',coverage='Santarém (PA), registros de 2011-01-11 a 2020-06-12',territory='Município de desembarque e comercialização na Feira do Pescado. Não informa município ou posição da captura.',origin='Origem extrativa ou de cultivo não identificada por registro. Não somar à aquicultura nem interpretar como captura extrativa exclusiva.',notes='Somente registros da feira; não representa total municipal ou cobertura diária completa. Ano 2020 termina em 12 de junho. O título original cita 2021, mas o arquivo não tem registros de 2021. Foram preservados todos os IDs: data, produto e peso iguais não comprovam duplicação de transações.',managed_by='prepare-santarem-fishing.py',reproduction='python scripts/prepare-municipal-fishing.py && python scripts/prepare-santarem-fishing.py',input_file=str(src.relative_to(root)),original_sha256=expected,transformations=['Soma exata por ano e nome popular com Decimal.','Espaços externos removidos e maiúsculas/minúsculas consolidadas. Não houve correção de grafia, inferência taxonômica ou união de nomes diferentes.','Unidade original Weight (metric ton) preservada em toneladas; nenhuma conversão de kg aplicada.','Não se excluíram zeros ou transações coincidentes; não se preencheram dias ausentes.'],raw_records=len(raw),species_labels=len(labels),aggregate_rows=len(rows),raw_total_t=str(total),year_coverage={str(y):dict(first_date=min(days),last_date=max(days),days_recorded=len(days)) for y,days in sorted(years.items())},dictionary={'source_id':'Identificador da fonte no painel.','codigo_ibge':'Município de desembarque atribuído pelo Atlas e conferido no IBGE.','especie':'Rótulo de nome popular da fonte; não é identificação científica.','desembarque_t':'Soma de Weight (metric ton), sem conversão.','registros':'Quantidade de transações da fonte no grupo.','dias_registrados':'Dias distintos com transações deste produto; não mede esforço.','esforco_horas':'Ausente para Santarém; não inferido.'})
p=d/'downloads/pesca-municipal-santarem-2011-2020.csv'
with p.open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
meta['sha256']=hashlib.sha256(p.read_bytes()).hexdigest();meta['csv']='downloads/'+p.name;meta['metadata_file']='downloads/'+p.stem+'.metadata.json';meta['original_file']='downloads/sources/'+src.name
(d/meta['metadata_file']).write_text(json.dumps(meta,ensure_ascii=False,indent=2))
old=json.loads((d/'municipal-fishing.json').read_text());oldmeta=old['metadata'];oldmeta.update(csv='downloads/pesca-municipal-arraial-1992-2008.csv',metadata_file='downloads/pesca-municipal-arraial-1992-2008.metadata.json',original_file='downloads/sources/arraial-bender-2014-original.xlsx',origin='Pesca artesanal extrativa; anchova registrada no ponto de desembarque do estudo.')
for r in old['rows']:r['source_id']='arraial'
combined=dict(sources={'santarem':meta,'arraial':oldmeta},rows=rows+old['rows'])
(d/'municipal-fishing.json').write_text(json.dumps(combined,ensure_ascii=False))
c=json.loads((d/'catalog.json').read_text());parent=next(x for x in c['items'] if x['id']=='doi:10.17632/ntprfhdypn');parent.update(notes=meta['notes']+' Arquivo original baixado e hash conferido em 04/10/2026; agregado disponível em Municípios → Pesca e desembarques.',coverage=meta['coverage'],formats=['CSV'],license_url=meta['license_url'])
item=dict(id=meta['id'],title=meta['title'],area='Pesca',topic='Captura e desembarque',access='prepared',scale='Município',publisher='Souza et al. · Mendeley Data',coverage=meta['coverage'],year=2020,description='Soma dos registros da feira por ano e nome popular. Origem extrativa ou de cultivo não identificada por registro.',notes=meta['notes'],source=source,license='CC BY 4.0',license_url=meta['license_url'],license_evidence=source,formats=['CSV'],tags=['Santarém','Pará','desembarque'],featured=130,layer='curated_subset',parent_dataset_id=parent['id'],prepared_at='2026-10-04',reuse_status='approved',managed_by=meta['managed_by'],file=meta['csv'],metadata_file=meta['metadata_file'],quality={'checked_at':'2026-10-04','sha256':meta['sha256'],'scope':'Integridade do arquivo original e conservação de massa e contagem na agregação anual verificadas. Não certifica a coleta original.','columns':list(rows[0]),'dictionary':meta['dictionary']})
c['items']=[x for x in c['items'] if x['id']!=item['id']]+[item];(d/'catalog.json').write_text(json.dumps(c,ensure_ascii=False))
print(json.dumps(dict(records=len(raw),labels=len(labels),annual_rows=len(rows),total_t=str(total),years=meta['year_coverage']),ensure_ascii=False))
